// https://projecteuler.net/problem=2

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

function evenFib() {
  let n1 = 1;
  let n2 = 2;
  let temp = 0;
  let sum = 0;

  while (n2 <= 4000000) {
    if (n2 % 2 === 0) {
      sum += n2
    }
    
    temp = n1 + n2;
    n1 = n2;
    n2 = temp;
    console.log("n1, n2, temp: ", n1, n2, temp)

  }
  return sum;
}

console.log(evenFib()); // answer: 4,613,732
